spring:
  application:
    name: exception
server:
  error:
    whitelabel:
      enabled: false
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: always